### PR TITLE
Feature/event based configurable global spinner

### PR DESCRIPTION
**Pull request by lpotepa**
[Review on Reviewable](https://reviewable.io/reviews/monterail/angular-global-spinner/1)

### CODE REVIEW

**Comment by lpotepa** [comment]
@monterail/dev Review pls

**Comment by jandudulski** [comment]
Please squash the commits.

---

Reviewed files:
- bower.json @ r2
- build/angular-global-spinner.min.js @ r1
- package.json @ r2
- README.md @ r2
- src/angular-global-spinner.coffee @ r2

---

<sup>**[build/angular-global-spinner.js, line 47 [r2]](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1#-JoYDPypMi1y1PBuOJfc)** ([raw file](https://github.com/monterail/angular-global-spinner/blob/6329a6c753c42b10cb0024c1721224aaf062cbf8/build/angular-global-spinner.js#L47)):</sup>

``` javascript
return _.every($http.pendingRequests, (function(sum, request) { return !!request.headers['X-Silent-Request'] }));
```

Shorter but I guess it will get the same results.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Comment by lpotepa** [comment]
done

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Comment by lpotepa** [comment]
<sup>**[build/angular-global-spinner.js, line 47 [r2]](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1#-JoYDPypMi1y1PBuOJfc)** ([raw file](https://github.com/monterail/angular-global-spinner/blob/6329a6c753c42b10cb0024c1721224aaf062cbf8/build/angular-global-spinner.js#L47)):</sup>
Please take a look at it now, after squash

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Comment by jandudulski** [comment]
<sup>**[build/angular-global-spinner.js, line 47 [r2]](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1#-JoYDPypMi1y1PBuOJfc)** ([raw file](https://github.com/monterail/angular-global-spinner/blob/6329a6c753c42b10cb0024c1721224aaf062cbf8/build/angular-global-spinner.js#L47)):</sup>
Did you push your changes? Nothing has changed here.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Comment by teamon** [comment]
@jan Please review .coffee files, .js are generated. (and should be

## generated before commit btw)

[image: Monterail]

Tymon Tobolski • CTO

at Monterail http://monterail.com/, Ruby development and design agency with
love

skype: nomaet • twitter: @iteamon http://twitter.com/iteamon

**Comment by lpotepa** [comment]
<sup>**[build/angular-global-spinner.js, line 47 [r2]](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1#-JoYDPypMi1y1PBuOJfc)** ([raw file](https://github.com/monterail/angular-global-spinner/blob/6329a6c753c42b10cb0024c1721224aaf062cbf8/build/angular-global-spinner.js#L47)):</sup>
Sorry, I forgot to rebuild the package earlier. Please check it now.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Comment by dgertych-monterail** [comment]
<sup>**[build/angular-global-spinner.js, line 47 [r2]](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1#-JoYDPypMi1y1PBuOJfc)** ([raw file](https://github.com/monterail/angular-global-spinner/blob/6329a6c753c42b10cb0024c1721224aaf062cbf8/build/angular-global-spinner.js#L47)):</sup>
@jandudulski @lpotepa we don't want to use methods from lodash/underscore it should be angular native only!

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Comment by jandudulski** [comment]
Reviewed files:
- build/angular-global-spinner.js @ r4
- build/angular-global-spinner.min.js @ r4
- src/angular-global-spinner.coffee @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Comment by jandudulski** [comment]
Looks good to me

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Comment by dgertych-monterail** [comment]
Commit is squashed OK, but shouldn't we adjust message to have uniqe entries?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-global-spinner/1)

**Pull request merged**
